name: JS SDK CI
on:
  pull_request:
    paths: ["packages/js-sdk/**", "specs/**"]
  push:
    branches: [main]
    paths: ["packages/js-sdk/**", "specs/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build -w packages/js-sdk
